# Site settings
title: Shihanmax
description: >
    Shihanmax's blogðŸš€
author: Shihanmax
email: shihanmax@foxmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://shihanmax.github.io" # the base hostname & protocol for your site
twitter_username: YourTwitterNo
github_username:  YourGitHubNo

# disqus_shortname: Test1

# Build settings
include: [_pages]
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title
sass:
    style: compressed

paginate: 10
paginate_path: "blog/page:num/"

gems:
  - jemoji
  - jekyll-sitemap